deployments:
  default:
    vm_size: 1G
    vm_storage_gb: 10G
    ready_wait: 120
    squash_pr_comments: true
    pipelines:
      - API Tests:
          dockerimage: phusion/baseimage:0.9.18
          build_steps:
            - echo something
            - apt-get install -y wget
            - ls -la
            - echo "finished"
          scripts:
            - echo "hello world"
      - Cart Tests:
          dockerimage: phusion/baseimage:0.9.18
          scripts:
            - echo "hello world"
      - Frontend Tests:
          dockerimage: phusion/baseimage:0.9.18
          scripts:
            - echo "hello world"              
