deployments:
  default:
    vm_size: 1G
    copy_files:
      - ~/.ssh/id_rsa ~/code/keys/
      - ~/.ssh/id_rsa.pub ~/code/keys/
    environment:
      TEST_VAL=42
    ready_wait: 120
    success_response_check_url: test--,/about
    subdomain_port_mapping:
      - test:80
      - test--test:81
      - another-test:8000
      - and--another-test:8000
