deployments:
  default:
    vm_size: 1G
    copy_files:
      - ~/.ssh/id_rsa ~/code/keys/
      - ~/.ssh/id_rsa.pub ~/code/keys/
    install:
      - docker build .
      - docker-compose up -d
    filename:
      ./docker-compose.yml
    context_path:
      ./
    ready_wait: 120
    subdomain_port_mapping:
      - test:80
      - test--test:81
      - another-test:8000
      - and--another-test:8000
