deployments:
  default:
    vm_size: 1G
    copy_files:
      - ~/.ssh/id_rsa ~/code/keys/
      - ~/.ssh/id_rsa.pub ~/code/keys/
    filename:
      ./docker-compose.yml
    pre_launch:
      - target: stuff-service
        command: run
        options: "{target} bash -c 'echo 111 && echo 222 && echo 333333'"
    ready_wait: 120
    subdomain_port_mapping:
      - test:80
      - test--test:81
      - another-test:8000
      - and--another-test:8000
