deployments:
  default:
    vm_size: 1G
    environment:
      TEST_VAL=42
    ready_wait: 120
    backend_wait: 20
    success_response_check_url: test--,/about
    subdomain_port_mapping:
      - test:80
      - test--test:81
      - another-test:8000
      - and--another-test:8000
    pre_terminate:
      - uname -a
      - ./src/scripts/script-2.sh
      - stuff-service:
        - cat ~/.bashrc
    post_launch:
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo domain is $SQUASH_DOMAIN'
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo branch id is $SQUASH_BRANCH_WITH_ID'
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo TEST_VAL2 is $TEST_VAL2'
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo TEST_VAL is $TEST_VAL'
